# Generated by Django 2.2.10 on 2020-06-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0005_opportunity_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updated_viewlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
