# Generated by Django 2.2.10 on 2020-06-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0006_updated_viewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='updated_viewlog',
            name='ud_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
