# Generated by Django 2.2.10 on 2020-08-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0010_updated_viewlog_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('Prospect', 'Prospect'), ('Interest', 'Interest'), ('Trial / POC', 'Trial / POC'), ('Proposal / Quote sent', 'Proposal / Quote sent'), ('Closed / Won', 'Closed / Won'), ('Aborted / Closed Lost', 'Aborted / Closed Lost')], default='Prospect', max_length=64, verbose_name='Stage'),
        ),
    ]
