# Generated by Django 2.2.4 on 2020-08-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0011_auto_20200817_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('Prospect', 'Prospect'), ('Interest', 'Interest'), ('Trial / POC', 'Trial / POC'), ('Proposal / Quote sent', 'Proposal / Quote sent'), ('Closed / Won', 'Closed / Won'), ('Aborted / Closed Lost', 'Aborted / Closed Lost')], max_length=64, verbose_name='Stage'),
        ),
    ]
