# Generated by Django 2.2.10 on 2020-06-22 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0004_opportunity_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
