# Generated by Django 2.2.10 on 2020-06-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
