# Generated by Django 2.2.10 on 2020-06-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_auto_20200626_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicehistory',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
