# Generated by Django 2.2.10 on 2020-08-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='read_status',
            field=models.CharField(default='unread', max_length=20),
        ),
    ]
