# Generated by Django 2.0 on 2020-04-24 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0006_auto_20200127_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voiceopen_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Close', 'Close')], max_length=64)),
                ('voiceopen_respond_within', models.TimeField(blank=True, default='00:00', null=True)),
                ('voiceopen_escalate_mail', models.CharField(default='', max_length=255)),
                ('voiceprogress_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Close', 'Close')], max_length=64)),
                ('voiceprogress_respond_within', models.TimeField(blank=True, default='00:00', null=True)),
                ('voiceprogress_escalate_mail', models.CharField(default='', max_length=255)),
                ('emailopen_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Close', 'Close')], max_length=64)),
                ('emailopen_respond_within', models.TimeField(blank=True, default='00:00', null=True)),
                ('emailopen_escalate_mail', models.CharField(default='', max_length=255)),
                ('emailprogress_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Close', 'Close')], max_length=64)),
                ('emailprogress_respond_within', models.CharField(default='0', max_length=255)),
                ('emailprogress_escalate_mail', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'sla',
            },
        ),
        migrations.CreateModel(
            name='SlaEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Close', 'Close')], max_length=64)),
                ('respond_within', models.TimeField(blank=True, default='00:00', null=True)),
                ('escalate_email', models.CharField(default='', max_length=255)),
                ('escalate_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slaemail',
            },
        ),
        migrations.CreateModel(
            name='SlaVoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Close', 'Close')], max_length=64)),
                ('respond_within', models.TimeField(blank=True, default='00:00', null=True)),
                ('escalate_mail', models.CharField(default='', max_length=255)),
                ('escalate_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slavoice',
            },
        ),
        migrations.CreateModel(
            name='UpdatedCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('oldvalue', models.CharField(max_length=100)),
                ('newvalue', models.CharField(max_length=100)),
                ('changedate', models.DateTimeField(auto_now_add=True)),
                ('changedby', models.CharField(default='null', max_length=100)),
            ],
            options={
                'db_table': 'updatecase',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='action_items',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='sla',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='case_assigned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, choices=[('Fire', 'Fire'), ('Typhoon', 'Typhoon'), ('EarthQuake', 'EarthQuake'), ('Tsunami', 'Tsunami'), ('Accident', 'Accident'), ('Medical', 'Medical'), ('Burglary', 'Burglary'), ('Others', 'Others')], default='Ambulance Service', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='closed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='phone1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Not Critical', 'Not Critical')], default='Not Critical', max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Close', 'Close')], default='Open', max_length=64),
        ),
        migrations.AddField(
            model_name='updatedcase',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
    ]
