# Generated by Django 2.2.10 on 2020-05-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20200425_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
