# Generated by Django 2.2.10 on 2020-06-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_case_parent_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='parent_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
