# Generated by Django 2.2.10 on 2020-06-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_auto_20200605_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='phone1',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
