# Generated by Django 2.2.4 on 2020-07-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_auto_20200627_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
    ]
