# Generated by Django 2.2.10 on 2020-05-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_auto_20200504_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contry',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='failedcontact',
            name='contry',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
