# Generated by Django 2.2.10 on 2020-06-08 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0015_auto_20200504_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contry',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='failedcontact',
            old_name='contry',
            new_name='country',
        ),
    ]
