# Generated by Django 2.2.4 on 2020-01-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_document_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
    ]
