# Generated by Django 2.2.4 on 2020-01-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, choices=[('Fire', 'Fire'), ('Typhoon', 'Typhoon'), ('EarthQuake', 'EarthQuake'), ('Tsunami', 'Tsunami'), ('Accident', 'Accident'), ('Medical', 'Medical'), ('Burglary', 'Burglary'), ('Others', 'Others')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Not Critical', 'Not Critical')], max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Close', 'Close')], max_length=64),
        ),
    ]
