# Generated by Django 2.2.4 on 2020-01-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20200118_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='name',
        ),
        migrations.AddField(
            model_name='case',
            name='phone1',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
