# Generated by Django 2.2.4 on 2020-01-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20200118_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='name',
            field=models.CharField(default=2, max_length=64, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
