# Generated by Django 2.2.4 on 2020-01-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='Name'),
        ),
    ]
