# Generated by Django 2.2.4 on 2020-01-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20200118_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='alternate_phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
