# Generated by Django 2.2.10 on 2020-06-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20200627_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
