# Generated by Django 2.2.10 on 2020-08-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_auto_20200627_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='account_name',
            field=models.CharField(blank=True, default='Company Name', max_length=255, null=True),
        ),
    ]
