# Generated by Django 2.2.4 on 2020-08-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_auto_20200805_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='reason_for_unqualified_lead',
            field=models.CharField(blank=True, choices=[('No Budget', 'No Budget'), ('Competitor', 'Competitor'), ('No Decision', 'No Decision'), ('No Power', 'No Power'), ('Lack of Vision', 'Lack of Vision'), ('Never Reached', 'Never Reached'), ('Wrong Information', 'Wrong Information')], max_length=255, null=True, verbose_name='Reason for lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('working', 'Working'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('recycled', 'Recycled'), ('closed', 'Closed')], max_length=255, null=True, verbose_name='Status of Lead'),
        ),
    ]
