# Generated by Django 2.2.2 on 2020-08-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_auto_20200805_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadid', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('notifi_status', models.CharField(default='unread', max_length=20)),
            ],
            options={
                'db_table': 'leadnotification',
            },
        ),
    ]
