# Generated by Django 2.2.2 on 2020-08-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='LeadNotification',
        ),
    ]
