# Generated by Django 2.2.4 on 2020-08-27 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_auto_20200826_1623'),
        ('leads', '0017_auto_20200827_1100'),
    ]

    operations = [
    ]
