# Generated by Django 2.2.10 on 2020-06-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_document_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency_settings',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
