# Generated by Django 2.2.4 on 2020-11-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20200620_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_service_access',
            field=models.BooleanField(default=False),
        ),
    ]
