# Generated by Django 2.2.4 on 2020-01-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='phone1',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
