# Generated by Django 2.2.10 on 2020-06-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_auto_20200519_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='parent_case',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
