# Generated by Django 2.2.4 on 2020-07-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_auto_20200714_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(default='', max_length=64, verbose_name='Name'),
        ),
    ]
