# Generated by Django 2.2.4 on 2020-08-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_auto_20200804_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='closed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
