# Generated by Django 2.2.4 on 2020-08-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_auto_20200810_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='closed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
