# Generated by Django 2.2.10 on 2020-08-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_auto_20200810_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='inbox_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
