# Generated by Django 2.2.2 on 2020-08-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_remove_case_inbox_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('notifi_status', models.CharField(default='unread', max_length=20)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
