# Generated by Django 2.2.4 on 2020-11-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_auto_20201130_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='asisignedcase_status',
            field=models.CharField(default='new_case', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=64),
        ),
    ]
