# Generated by Django 2.2.4 on 2020-12-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_auto_20201130_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='colorcode',
            field=models.CharField(default='#CCC', max_length=255),
        ),
    ]
