# Generated by Django 2.2.4 on 2020-12-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0024_case_colorcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='asisignedcase_status',
            new_name='assignedcase_status',
        ),
    ]
