# Generated by Django 2.2.10 on 2020-04-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20200424_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone2',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
