# Generated by Django 2.2.4 on 2020-04-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20200425_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_inbox', models.TextField()),
                ('description', models.TextField()),
                ('username', models.CharField(default='', max_length=50, null=True)),
                ('from_address', models.EmailField(default='', max_length=50)),
                ('to_address', models.EmailField(default='', max_length=50)),
                ('status', models.CharField(default=0, max_length=10, null=True)),
            ],
            options={
                'db_table': 'emailinfo',
            },
        ),
    ]
