# Generated by Django 2.2.4 on 2020-06-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20200425_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
