# Generated by Django 2.2.10 on 2020-05-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0013_blockeddomain_blockedemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contry',
        ),
        migrations.RemoveField(
            model_name='failedcontact',
            name='contry',
        ),
    ]
