# Generated by Django 2.2.10 on 2020-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_emailinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
