# Generated by Django 2.2.4 on 2019-12-26 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractorname', models.CharField(max_length=100)),
                ('contractorid', models.CharField(max_length=100)),
                ('companyname', models.CharField(max_length=100)),
                ('mailid', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('validity', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('qrimage', models.CharField(default='null', max_length=100)),
            ],
            options={
                'db_table': 'contractor',
            },
        ),
        migrations.CreateModel(
            name='EntryExit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('intime', models.CharField(max_length=100)),
                ('outtime', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'entryexit',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=100)),
                ('staffid', models.CharField(max_length=100)),
                ('desgination', models.CharField(max_length=100)),
                ('mailid', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorname', models.CharField(max_length=100)),
                ('mailid', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100, null=True)),
                ('qrimage', models.CharField(default='null', max_length=100)),
            ],
            options={
                'db_table': 'visitor',
            },
        ),
    ]
