# Generated by Django 2.1 on 2020-01-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('developer', models.CharField(blank=True, default='', max_length=10, null=True)),
            ],
            options={
                'db_table': 'sample',
            },
        ),
    ]
